server:
  port: 8888
spring:  application:    name: configserver  cloud:    config:      server:        git:          uri: https://github.com/bhokumar/cloud-config.git
eureka:  client:    service-url:      defaulZone: http://localhost:8761/eureka
management:  endpoints:    web:      exposure:        include:        - "*"      